export const LOAD_ROUTINES = 'LOAD_ROUTINES';
export const LOAD_ROUTINE = 'LOAD_ROUTINE';
export const POST_ROUTINES = 'POST_ROUTINES';
export const LOAD_EXERCISES = 'LOAD_EXERCISES';
export const LOAD_EXERCISE = 'LOAD_EXERCISE';
export const POST_EXERCISES = 'POST_EXERCISES';
export const LOAD_CALENDAR = 'LOAD_CALENDAR';
export const ADD_TO_CALENDAR = 'ADD_TO_CALENDAR';
export const POST_CALENDAR = 'POST_CALENDAR';

export const ADD_ROUTINE_TO_CALENDAR = 'ADD_ROUTINE_TO_CALENDAR';

export const ROUTINES_FAILED = 'ROUTINES_FAILED';
export const EXERCISES_FAILED = 'EXERCISES_FAILED';
export const CALENDAR_FAILED = 'CALENDAR_FAILED';
export const DELETE_ROUTINE = 'DELETE_ROUTINE';
export const REMOVE_EXERCISE_FROM_ROUTINE = 'REMOVE_EXERCISE_FROM_ROUTINE';

export const ROUTINES_LOADING = 'ROUTINES_LOADING';
export const EXERCISES_LOADING = 'EXERCISES_LOADING';
export const CALENDAR_LOADING = 'CALENDAR_LOADING';
